Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:09:28Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:09:28Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:14:27Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:09:28Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:14:27Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:19:27Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:09:28Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:14:27Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:19:27Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-05T18:24:29Z <Greenlet at 0x7fd2ab321ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd2abec5b50>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:52:28Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:52:28Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:56:21Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:52:28Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:56:21Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:01:23Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:52:28Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:56:21Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:01:23Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:06:22Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:41:27Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:50:58Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:52:28Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T08:56:21Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:01:23Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:06:22Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:11:22Z <Greenlet at 0x7ff5afb4aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff5b06f0a10>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:21:07Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:21:07Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:25:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:21:07Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:25:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:30:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:21:07Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:25:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:30:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:35:57Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:21:07Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:25:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:30:56Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:35:57Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-06T09:40:58Z <Greenlet at 0x7f08c5b46ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f08c66dbb50>>(17, None)> failed with HaltServer

Using backend: pytorch
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
Using backend: pytorch
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
Using backend: pytorch
Using backend: pytorch
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
Using backend: pytorch
python3: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python3: can't open file '../Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
python3: can't open file '/HML/Decision/MAM_Factor-main/test.py': [Errno 2] No such file or directory
Using backend: pytorch

Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-11T13:56:40Z <Greenlet at 0x7f13b26c9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f13b3274b90>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-11T13:56:40Z <Greenlet at 0x7f13b26c9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f13b3274b90>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-11T14:01:27Z <Greenlet at 0x7f13b26c9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f13b3274b90>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch

Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:48:18Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:48:18Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:53:25Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:48:18Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:53:25Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T12:59:32Z <Greenlet at 0x7fba6584fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fba663e9990>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T13:13:16Z <Greenlet at 0x7fcb8a86bef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fcb8b40ec10>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T13:20:21Z <Greenlet at 0x7f4c09ec8ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f4c0aa75a90>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T13:20:21Z <Greenlet at 0x7f4c09ec8ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f4c0aa75a90>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T13:27:14Z <Greenlet at 0x7f4c09ec8ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f4c0aa75a90>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch

Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 63 (or pid file 'log/gunicorn.pid' is stale)

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:33:23Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:33:23Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:38:02Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:33:23Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:38:02Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-18T14:43:05Z <Greenlet at 0x7fb2a70d9ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb2a7c70850>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-20T07:47:17Z <Greenlet at 0x7f5853a6def0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f585460fad0>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-20T07:47:17Z <Greenlet at 0x7f5853a6def0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f585460fad0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-20T07:52:16Z <Greenlet at 0x7f5853a6def0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f585460fad0>>(17, None)> failed with HaltServer

Using backend: pytorch

Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 66 (or pid file 'log/gunicorn.pid' is stale)

Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:04:39Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:04:39Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:09:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:04:39Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:09:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:14:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:04:39Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:09:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:14:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-08-28T07:19:40Z <Greenlet at 0x7fd675e0aef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fd6769ad7d0>>(17, None)> failed with HaltServer

Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
Using backend: pytorch
Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
Using backend: pytorch
Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'M4' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'M4' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
Using backend: pytorch
Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --task: invalid choice: 'None' (choose from 'S4', 'S10', 'M5')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: '300' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: '9241' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: '300' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: '9241' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: '9241' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: 'case9241--task' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: 'case9241--task' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: invalid choice: 'case9241--task' (choose from 'case118', 'case300', 'case9241')
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:20:29Z <Greenlet at 0x7f3a3a138ef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f3a3acdfb10>>(17, None)> failed with HaltServer

Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:27:47Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:27:47Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:32:50Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:27:47Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:32:50Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-09-12T06:37:51Z <Greenlet at 0x7ff30291fef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7ff3034c3b90>>(17, None)> failed with HaltServer

Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument

Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)


Error: Already running on PID 78 (or pid file 'log/gunicorn.pid' is stale)

usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:32:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:32:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:37:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:32:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:37:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:42:53Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:32:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:37:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:42:53Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:47:54Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:22:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:27:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:32:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:37:52Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:42:53Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:47:54Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/hml/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2023-10-16T01:52:54Z <Greenlet at 0x7fe81fbeeef0: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fe820798a50>>(17, None)> failed with HaltServer

Using backend: pytorch
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
usage: test.py [-h] [--case {case118,case300,case9241}] [--task {S4,S10,M5}]
test.py: error: argument --case: expected one argument
